kind: Namespace
apiVersion: v1
metadata:
  name: salesforce-prod
  labels:
    name: salesforce-prod
spec: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: salesforce-prod
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
